mysql: &using
  adapter: mysql
  host: dev.twork.taobao.net
  password: auto
  database: tam_development
  username: auto
  encoding: utf8
development:
 <<: *using
production:
 database: tam_production
 <<: *using        
redmine:            
 adapter: mysql
 host: dev.twork.taobao.net
 password: auto
 database: redmine
 username: auto
 encoding: utf8  
test:
 database: twork_test
 <<: *using
qc_admin:
  adapter: oracle
  database: qcsite
  host: ""
  password: tdtdtd
  username: qc_db
  encoding: utf8
qc_user:
  adapter: oracle
  database: qcsite
  host: ""
  password: qcuser
  username: qcuser
  encoding: utf8
db_platform:
 adapter: mysql
 host: 192.168.210.2
 password: wenlang
 database: phr
 username: wenlang
 encoding: utf8